{{ if eq (.Values.baffleMongodb.replication.enabled | toString) "true" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: baffle-mongodb-arb
  name: baffle-mongodb-arb
spec:
  ports:
  - port: {{ .Values.baffleMongodb.replication.arbiterPort }}
    protocol: TCP
    targetPort: 27017
  selector:
    app: baffle-mongodb-arb
  type: {{ .Values.baffleMongodb.replication.arbiterType }}
{{ end }}
