apiVersion: v1
kind: Service
metadata:
  labels:
    app: baffle-manager
  name: baffle-manager
spec:
  ports:
  - port: {{ .Values.baffleManager.service.port }}
    protocol: TCP
    targetPort: 8553
  selector:
    app: baffle-manager
  type: {{ .Values.baffleManager.service.type }}
