apiVersion: apps/v1
kind: Deployment
metadata:
  name: baffle-manager
  labels:
    app: baffle-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: baffle-manager
  template:
    metadata:
      labels:
        app: baffle-manager
    spec:
      serviceAccountName: baffle-sa
      securityContext:
        fsGroup: 5000
        runAsUser: 5000
        runAsGroup: 5000
      containers:
      - name: baffle-manager
        image: {{ .Values.baffleManager.image | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: baffle-ss-cm
        {{ if eq .Values.baffleManager.SSO.SSO_OIDC "enabled" }}
        - configMapRef:
            name: baffle-sso-cm
        {{end}}
        env:
          {{ if .Values.baffleMongodb.IsExternal | default false }}
          - name: MONGO_URL
            value: {{ .Values.baffleMongodb.EXT_MONGO_URL }}
              #- name: CA_CERTS_STRING
              #valueFrom:
              #secretKeyRef:
              # name: baffle-secret
              # key: baffle-mongodb-cacert
          {{ else }}
          {{- if .Values.baffleMongodb.replication.enabled | default false }}
          - name: MONGO_URL
            value: {{ .Values.baffleMongodb.replication.MONGO_URL }}
          {{ else }}
          - name: MONGO_IP
            value: "baffle-mongodb"
          - name: MONGO_PORT
            value: "27017"
          {{ end }}
          {{ end }}
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: baffle-secret
                key: baffle-mongodb-username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: baffle-secret
                key: baffle-mongodb-password
          - name: INIT_PASS
            value: {{ .Values.baffleManager.initPass }}
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: baffle-secret
                key: baffle-keystore-password
          - name: CA_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: baffle-secret
                key: baffle-truststore-password
          - name: SPRING_PROFILES_ACTIVE
            value: docker_prod
          - name: BS_CONFIG_PATH
            value: /opt/baffle
          {{ if eq .Values.baffleManager.SSO.SSO_OIDC "enabled" }}
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: baffle-secret
                key: sso-oidc-client-secret
          {{ end}}
          {{ if eq .Values.baffleManager.secretStore.STORE_TYPE "HASHICORP" }}
          - name: SECRET_STORE_TOKEN
            valueFrom:
              secretKeyRef:
                name: baffle-secret
                key: secret-store-token
          {{ end}}
          {{ if eq .Values.baffleManager.secretStore.STORE_TYPE "AZURE" }}
          - name: SECRET_STORE_SECRET
            valueFrom:
              secretKeyRef:
                name: baffle-secret
                key: secret-store-secret
          {{ end}}
        resources:
          limits:
            cpu: {{ .Values.baffleManager.resources.limits.cpu | quote }}
            memory: {{ .Values.baffleManager.resources.limits.memory | quote }}
          requests:
            cpu: {{ .Values.baffleManager.resources.requests.cpu | quote }}
            memory: {{ .Values.baffleManager.resources.requests.memory | quote }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
      {{ end}}
