apiVersion: v1
kind: Secret
metadata:
  name: baffle-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  baffle-keystore-password: a2V5c3RvcmU=
  baffle-truststore-password: Y2hhbmdlaXQ=	
  {{- if .Release.IsInstall }}
  {{- if .Values.baffleMongodb.IsExternal | default false }}
  baffle-mongodb-username: {{ .Values.baffleMongodb.EXT_MONGO_USER | b64enc }}
  baffle-mongodb-password: {{ .Values.baffleMongodb.EXT_MONGO_PASS | b64enc }}
  {{- else }}
  baffle-mongodb-username: {{ "baffle_admin" | b64enc }}
  baffle-mongodb-password: {{ "baffle_pass_09876" | b64enc }}
  {{ if .Values.baffleMongodb.replication.enabled | default false }}
  baffle-mongodb-repl-key: {{ .Values.baffleMongodb.replication.replicationKey | quote }}
  {{ end }}
  {{- end }}
  {{ if eq .Values.baffleManager.SSO.SSO_OIDC "enabled" }}
  sso-oidc-client-secret: {{ .Values.baffleManager.SSO.secrets.OIDC_CLIENT_SECRET | b64enc }}
  {{ end }}
  {{ if eq .Values.baffleManager.secretStore.STORE_TYPE "HASHICORP" }}
  secret-store-token: {{ .Values.baffleManager.secretStore.secrets.SECRET_STORE_TOKEN | b64enc }}
  {{ end }}
  {{ if eq .Values.baffleManager.secretStore.STORE_TYPE "AZURE" }}
  secret-store-secret: {{ .Values.baffleManager.secretStore.secrets.SECRET_STORE_SECRET | b64enc }}
  {{ end }}
  {{- else }}
  {{- with lookup "v1" "Secret" .Release.Namespace "baffle-secret" }}
  baffle-mongodb-username: {{ index .data "baffle-mongodb-username" }}
  baffle-mongodb-password: {{ index .data "baffle-mongodb-password" }}
  baffle-mongodb-cacert: {{ index .data "baffle-mongodb-cacert" }}
  {{- else }}
  baffle-mongodb-username: {{ "baffle_admin" | b64enc }}
  baffle-mongodb-password: {{ "baffle_pass_09876" | b64enc }}
  baffle-mongodb-cacert: ""
  {{- end }}
  {{ if .Values.baffleMongodb.replication.enabled | default false }}
  {{- with lookup "v1" "Secret" .Release.Namespace "baffle-secret" }}
  baffle-mongodb-repl-key: {{ index .data "baffle-mongodb-repl-key" }}
  {{- else }}
  baffle-mongodb-repl-key: {{ .Values.baffleMongodb.replication.replicationKey | quote }}
  {{- end }}
  {{ end }}
  {{ if eq .Values.baffleManager.SSO.SSO_OIDC "enabled" }}
  {{- with lookup "v1" "Secret" .Release.Namespace "baffle-secret" }}
  sso-oidc-client-secret: {{ index .data "sso-oidc-client-secret" }}
  {{- else }}
  sso-oidc-client-secret: {{ .Values.baffleManager.SSO.secrets.OIDC_CLIENT_SECRET | b64enc }}
  {{- end }}
  {{ end }}
  {{ if eq .Values.baffleManager.secretStore.STORE_TYPE "HASHICORP" }}
  {{- with lookup "v1" "Secret" .Release.Namespace "baffle-secret" }}
  secret-store-token: {{ index .data "secret-store-token" }}
  {{- else }}
  secret-store-token: {{ .Values.baffleManager.secretStore.secrets.SECRET_STORE_TOKEN | b64enc }}
  {{- end }}
  {{ end }}
  {{ if eq .Values.baffleManager.secretStore.STORE_TYPE "AZURE" }}
  {{- with lookup "v1" "Secret" .Release.Namespace "baffle-secret" }}
  secret-store-secret: {{ index .data "secret-store-secret" }}
  {{- else }}
  secret-store-secret: {{ .Values.baffleManager.secretStore.secrets.SECRET_STORE_SECRET | b64enc }}
  {{- end }}
  {{ end }}
  {{- end }}
