{{- if eq .Values.baffleManager.SSO.SSO_OIDC "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: baffle-sso-cm
data:
  ORG_NAME: {{ .Values.baffleManager.SSO.ORG_NAME | quote }}
  SSO_OIDC: {{ .Values.baffleManager.SSO.SSO_OIDC | quote }}
  SSO_OIDC_PROVIDER: {{ .Values.baffleManager.SSO.SSO_OIDC_PROVIDER | quote }}
  OIDC_ISSUER_URI: {{ .Values.baffleManager.SSO.OIDC_ISSUER_URI | quote }}
  OIDC_CLIENT_ID: {{ .Values.baffleManager.SSO.OIDC_CLIENT_ID | quote }}
  OIDC_SCOPE: {{ .Values.baffleManager.SSO.OIDC_SCOPE | quote }}
  SYS_ADMIN_GROUP_NAME: {{ .Values.baffleManager.SSO.OIDC_SYS_ADMIN_GROUP_NAME | quote }}
  GROUP_CLAIM_NAMES: {{ .Values.baffleManager.SSO.OIDC_CLAIM_NAME | quote }}
  API_URL: {{ .Values.baffleManager.SSO.API_URL | quote }}
  DEPLOYMENT_URL: {{ .Values.baffleManager.SSO.DEPLOYMENT_URL | quote }}
{{- end }}
