apiVersion: v1
kind: Service
metadata:
  labels:
    app: baffle-web
  name: baffle-web
spec:
  ports:
  - port: {{ .Values.baffleWeb.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: baffle-web
  type: {{ .Values.baffleWeb.service.type }}
